server:
  port: 8000
spring:
  application:
    name: cambio-service
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/cambio_service
    username: cambioservice
    password: cambioservice
