server:
  port: 8000
spring:
  application:
    name: cambio-service
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/cambio_service
    username: cambioservice
    password: cambioservice
  sleuth:
    sampler:
      probability: 1.0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
springdoc:
  show-actuator: true
  api-docs:
    path: cambio-service/v3/api-docs