server:
  port: 8100
spring:
  application:
    name: book-service
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5433/book_service
    username: bookservice
    password: bookservice
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
resilience4j:
  retry:
    instances:
      resilience:
        max-attempts: 5