CREATE TABLE book (
  id INTEGER PRIMARY KEY,
  author VARCHAR(200),
  launch_date DATE NOT NULL,
  price DECIMAL(65,2) NOT NULL,
  title VARCHAR(250)
);

CREATE SEQUENCE book_seq AS INTEGER START WITH 1 INCREMENT BY 1;